baseurl: '/'
permalink: pretty
title: 'IPSM Approach'
default_lang: en

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "38px"
  desktop_width: "264px"

home:
  limit_documents: 6

collections:
  documents:
    output: true
    sort_by: weight
  documents_zh:
    output: true
    sort_by: weight
    permalink: /zh/documents/:name/
  documents_es:
    output: true
    sort_by: weight
    permalink: /es/documents/:name/
  documents_fr:
    output: true
    sort_by: weight
    permalink: /fr/documents/:name/

defaults:
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "document"
      lang: en
  - scope:
      path: ""
      type: "documents_zh"
    values:
      layout: "document"
      lang: zh
  - scope:
      path: "zh"
    values:
      lang: zh
  - scope:
      path: ""
      type: "documents_es"
    values:
      layout: "document"
      lang: es
  - scope:
      path: "es"
    values:
      lang: es
  - scope:
      path: ""
      type: "documents_fr"
    values:
      layout: "document"
      lang: fr
  - scope:
      path: "fr"
    values:
      lang: fr

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - scripts
